oneului_bab/config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('content.urls')),
    path('user/',include('user.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

oneului_bab/user/urls.py
from django.urls import path
from user.views import LoginView, LogoutView, FindIDView, FindPasswordView, JoinView, ChangePasswordView, UserInfoeView

urlpatterns = [
    path('login/',LoginView.as_view(),name="loginview"),
    path('logout/',LogoutView.as_view(),name="logoutview"),
    path('join/',JoinView.as_view(),name="joinview"),
    path('findid/',FindIDView.as_view(),name="findidview"),
    path('findpassword/',FindPasswordView.as_view(),name="findpasswordview"),
    path('changepassword/<str:emailcode>/', ChangePasswordView.as_view(), name='changepasswordview'),
    path('<int:pk>/update/', UserInfoeView.update, name='update'),
    path('<int:pk>/changepassword/', UserInfoeView.chagepassword, name='changepassword'),
    path('<int:pk>/', UserInfoeView.detail, name='detail'),
]

oneului_bab/user/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('이메일을 설정해야 합니다')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_active', False)

        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_active') is not True:
            raise ValueError('Superuser must have is_active=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True, blank=False)
    name = models.CharField(_('name'), max_length=30, blank=False)
    nickname = models.CharField(_('nickname'), max_length=30, blank=False,default=name)
    birth_date = models.DateField(_('birth date'), blank=True, default=0000-00-00)
    is_staff = models.BooleanField(_('staff status'), default=False, help_text=_('Designates whether the user can log into this admin site.'),)
    is_active = models.BooleanField(_('active'), default=False, help_text=_('Designates whether this user should be treated as active. ' 'Unselect this instead of deleting accounts.'),)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name','nickname','birth_date']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        swappable = 'AUTH_USER_MODEL'

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

oneului_bab/user/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

from user.models import User
from django.contrib.auth.forms import UserChangeForm

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User()
        fields = ['nickname', 'name', 'email']

oneului_bab/user/views.py
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView, LogoutView
from django.views import View
from django.contrib import messages
from user.forms import CustomLoginForm
from .models import User
from django.shortcuts import render, HttpResponseRedirect, redirect, get_object_or_404  
import smtplib
from email.mime.text import MIMEText
from datetime import datetime
#########################
import json
import os
import smtplib
from email.mime.text import MIMEText

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
secrets_file = os.path.join(BASE_DIR, 'secrets.json')
##########################

# 로그인
class LoginView(LoginView):
    authentication_form = CustomLoginForm
    template_name = 'user/login.html'

    def form_invalid(self, form):
        messages.error(self.request, '아이디 또는 비밀번호를 잘못 입력했습니다. \n입력하신 내용을 다시 확인해주세요.', extra_tags='danger')
        return super().form_invalid(form)
    
    def form_valid(self, form):
        redirect_to = reverse_lazy('main')

        user = form.get_user()
        authenticated_user = authenticate(
            username=user.email,
            password=form.cleaned_data.get('password')
        )

        if authenticated_user is not None:
            login(self.request, authenticated_user)
            self.request.session['email'] = user.email
            return HttpResponseRedirect(redirect_to)

        return super().form_invalid(form)
    
# 로그아웃
class LogoutView(LogoutView):
    next_page = reverse_lazy('loginview')

    def get_next_page(self):
        next_page = super().get_next_page()
        messages.success(self.request, '로그아웃되었습니다.', extra_tags='success')
        return self.next_page

# 회원가입
class JoinView(View):
    template_name = 'user/join.html'
    def get(self, request):
        return render(request, 'user/join.html')

    def send_email_code(self, request, email):
        import random
        code = random.randint(100000, 999999)
        message = f"이메일 인증 코드 입니다. : {code}"
        msg = MIMEText(message)
        msg['Subject'] = '오늘의 밥 : 회원가입 인증 코드'
        msg['From'] = 'jjong015189@gmail.com'
        msg['To'] = email

        with open(secrets_file) as f:
            secrets = json.load(f)

        s = smtplib.SMTP('smtp.gmail.com', 587)
        s.starttls()
        s.login('jjong015189@gmail.com', secrets['GMAIL_KEY'])
        s.sendmail('jjong015189@gmail.com', [email], msg.as_string())
        s.quit()
        request.session['email_verification_code'] = code
        return code

    def check_email_code(self, request):
        emailcode = request.POST['emailcode']
        if 'email_verification_code' in request.session:
            if int(emailcode) == request.session['email_verification_code']:
                return True
        return False
    
    def post(self, request):
        if request.POST.get('submit') == 'email-verify':
            email = request.POST['email']
            password = request.POST['password']
            confirm_password = request.POST['confirm_password']
            name = request.POST['name']
            nickname = request.POST['nickname']
            birthdate_year = request.POST['birthdate_year']
            birthdate_month = request.POST['birthdate_month']
            birthdate_days = request.POST['birthdate_days']
            birthdate = birthdate_year + "-" + birthdate_month + "-" + birthdate_days
            emailcode = request.POST['emailcode']
            info = {'email': email, 'password': password, 'confirm_password': confirm_password, 'name': name, 'nickname': nickname, 'birthdate_year': birthdate_year, 'birthdate_month': birthdate_month, 'birthdate_days': birthdate_days, 'emailcode': emailcode}
            
            if password != confirm_password:
                messages.error(request, '비밀번호와 비밀번호 확인이 일치하지 않습니다.')
                return HttpResponse(render(request, 'user/join.html', info))
            
            if User.objects.filter(email=email).exists():
                messages.error(request, '이미 존재하는 이메일입니다.')
                return HttpResponse(render(request, 'user/join.html', info))
            
            if User.objects.filter(nickname=nickname).exists():
                messages.error(request, '이미 존재하는 닉네임입니다.')
                return HttpResponse(render(request, 'user/join.html', info))

            self.send_email_code(request, email)
            
            messages.success(request, '인증번호가 전송되었습니다.')
            return HttpResponse(render(request, 'user/join.html', info))
        elif request.POST.get('submit') == 'join':
            email = request.POST['email']
            password = request.POST['password']
            confirm_password = request.POST['confirm_password']
            name = request.POST['name']
            nickname = request.POST['nickname']
            birthdate_year = request.POST['birthdate_year']
            birthdate_month = request.POST['birthdate_month']
            birthdate_days = request.POST['birthdate_days']
            birthdate = birthdate_year + "-" + birthdate_month + "-" + birthdate_days
            emailcode = request.POST['emailcode']
            info = {'email': email, 'password': password, 'confirm_password': confirm_password, 'name': name, 'nickname': nickname, 'birthdate_year': birthdate_year, 'birthdate_month': birthdate_month, 'birthdate_days': birthdate_days, 'emailcode': emailcode}
            
            if password != confirm_password:
                messages.error(request, '비밀번호와 비밀번호 확인이 일치하지 않습니다.')
                return HttpResponse(render(request, 'user/join.html', info))
            
            if User.objects.filter(email=email).exists():
                messages.error(request, '이미 존재하는 이메일입니다.')
                return HttpResponse(render(request, 'user/join.html', info))
            
            if User.objects.filter(nickname=nickname).exists():
                messages.error(request, '이미 존재하는 닉네임입니다.')
                return HttpResponse(render(request, 'user/join.html', info))
            
            if emailcode == "":
                messages.error(request, '이메일 인증을 해주세요')
                return HttpResponse(render(request, 'user/join.html', info))
            else:
                if self.check_email_code(request) == True:
                    messages.success(request, '회원가입이 완료되었습니다.')
                    user = User.objects.create_user(email=email, password=password, name=name, nickname=nickname, birth_date=birthdate,is_active=True)
                    user.save()
                    user = authenticate(email=email, password=password)
                    login(request, user)
                elif self.check_email_code(request) == False:
                    messages.success(request, '인증번호가 잘못되었습니다. 다시 확인해주세요.')
                    return HttpResponse(render(request, 'user/join.html', info))
        return redirect('loginview')

# 아이디 찾기
class FindIDView(View):
    template_name = 'user/find_ID.html'
    def get(self, request):
        return render(request, 'user/find_ID.html')
    
    def post(self, request):
        if request.POST.get('submit') == 'id_check':
            email = request.POST['email']
            name = request.POST['name']
            birthdate_year = request.POST['birthdate_year']
            birthdate_month = request.POST['birthdate_month']
            birthdate_days = request.POST['birthdate_days']
            birthdate = birthdate_year + "-" + birthdate_month + "-" + birthdate_days
            info = {'email': email,'name': name,'birthdate_year': birthdate_year, 'birthdate_month': birthdate_month, 'birthdate_days': birthdate_days}

            try:
                user = User.objects.get(email=email, name=name, birth_date=birthdate)
                if str(user) == email:
                    messages.info(request, '회원 정보가 일치합니다.')
                else:
                    messages.error(request, '회원정보가 없거나 잘못되었습니다.')
                    return render(request, 'user/find_ID.html', info)
            except:
                messages.error(request, '회원정보가 없거나 잘못되었습니다.')
                return render(request, 'user/find_ID.html', info)

            return HttpResponse(render(request, 'user/find_ID.html', info))

# 비밀번호 찾기
class FindPasswordView(View):
    template_name = 'user/find_Password.html'

    # 비밀번호 인증 코드 보내기
    def send_email_password_code(self, request, email):
        import random
        code = random.randint(100000, 999999)
        message = f"이메일 인증 코드 입니다. : {code}"
        msg = MIMEText(message)
        msg['Subject'] = '오늘의 밥 : 비밀번호 인증 코드'
        msg['From'] = 'jjong015189@gmail.com'
        msg['To'] = email

        with open(secrets_file) as f:
            secrets = json.load(f)

        s = smtplib.SMTP('smtp.gmail.com', 587)
        s.starttls()
        s.login('jjong015189@gmail.com', secrets['GMAIL_KEY'])
        s.sendmail('jjong015189@gmail.com', [email], msg.as_string())
        s.quit()
        request.session['email_verification_code'] = code
        return code

    def check_email_password_code(self, request):
        emailcode = request.POST['emailcode']
        if 'email_verification_code' in request.session:
            if int(emailcode) == request.session['email_verification_code']:
                return True
        return False
    
    def get(self, request):
        return render(request, 'user/find_Password.html')

    def post(self, request):
        if request.POST.get('submit') == 'email_verify':
            email = request.POST['email']
            name = request.POST['name']
            birthdate_year = request.POST['birthdate_year']

oneului_bab/templates/user/change_Password.html
{% extends 'index.html' %}
{% load static %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script>
    $.ajaxSetup({
        headers: { "X-CSRFToken": '{{csrf_token}}' }
    });
</script>
{% endblock script %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/find_account.css' %}">
{% endblock css %}

{% block ad1 %}
{% endblock ad1 %}

{% block account_info %}
<div class="findaccount_container">
    <form class="findaccount_form" method="POST">
        <h3>비밀번호 변경</h3>
        <div>아이디는 가입하신 이메일과 동일합니다.</div>
        <div class="change_password_info">이메일</div>
        <input class="join_info_input" type="email" name="email" readonly value="{{email}}">
        <div class="change_password_info">새 비밀번호</div>
        <input class="join_info_input" type="password" name="password" required value="{{password}}">
        <div class="change_password_info">비밀번호 재확인</div>
        <input class="join_info_input" id="change_password_info_last" type="password" name="confirm_password" required value="{{confirm_password}}">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% csrf_token %}
        <button class="change_password_input" id="change_password_button" type="submit" name="submit" value="change_password">비밀번호 변경</button>
    </form>
    <div class="info_find_warp">
        <a class="info_find" href="/user/findid">아이디 찾기</a>
        <div class="info_find">|</div>
        <a class="info_find" href="/user/findpassword">비밀번호 찾기</a>
        <div class="info_find">|</div>
        <a class="info_find" href="/user/join">회원가입</a>
    </div>
</div>
{% endblock account_info %}

oneului_bab/templates/user/find_ID.html
{% extends 'index.html' %}
{% load static %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script>
    $.ajaxSetup({
        headers: { "X-CSRFToken": '{{csrf_token}}' }
    });
</script>
{% endblock script %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/find_account.css' %}">
{% endblock css %}

{% block ad1 %}
{% endblock ad1 %}

{% block account_info %}
<div class="findaccount_container">
    <form class="findaccount_form" method="POST">
        <h3>아이디 찾기</h3>
        <div>아이디는 가입하신 이메일과 동일합니다.</div>
        <div class="find_id_info">이메일</div>
        <input class="find_id_input" type="email" name="email" required value="{{email}}">
        <div class="find_id_info">이름</div>
        <input class="find_id_input" type="text" name="name" required value="{{name}}">
        <div class="find_id_info">생년월일</div>
        <div class="find_id_input" id="birthdate_info">
            <input class="find_id_info_birthdate" type="text" name="birthdate_year" required value="{{birthdate_year}}">
            <select class="find_id_info_birthdate" name="birthdate_month" required>
                <option value="" {% if not birthdate_month %}selected{% endif %} disabled hidden>월</option>
                <option value="1" {% if birthdate_month == '1' %}selected{% endif %}>1월</option>
                <option value="2" {% if birthdate_month == '2' %}selected{% endif %}>2월</option>
                <option value="3" {% if birthdate_month == '3' %}selected{% endif %}>3월</option>
                <option value="4" {% if birthdate_month == '4' %}selected{% endif %}>4월</option>
                <option value="5" {% if birthdate_month == '5' %}selected{% endif %}>5월</option>
                <option value="6" {% if birthdate_month == '6' %}selected{% endif %}>6월</option>
                <option value="7" {% if birthdate_month == '7' %}selected{% endif %}>7월</option>
                <option value="8" {% if birthdate_month == '8' %}selected{% endif %}>8월</option>
                <option value="9" {% if birthdate_month == '9' %}selected{% endif %}>9월</option>
                <option value="10" {% if birthdate_month == '10' %}selected{% endif %}>10월</option>
                <option value="11" {% if birthdate_month == '11' %}selected{% endif %}>11월</option>
                <option value="12" {% if birthdate_month == '12' %}selected{% endif %}>12월</option>
            </select>
            <input class="find_id_info_birthdate" type="text" name="birthdate_days" required value="{{birthdate_days}}">
        </div>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% csrf_token %}
        <button class="find_id_input" id="fine_id_button" type="submit" name="submit" value="id_check">확인하기</button>
    </form>
    <div class="info_find_warp">
        <a class="info_find" href="/user/findid">아이디 찾기</a>
        <div class="info_find">|</div>
        <a class="info_find" href="/user/findpassword">비밀번호 찾기</a>
        <div class="info_find">|</div>
        <a class="info_find" href="/user/join">회원가입</a>
    </div>
</div>
{% endblock account_info %}

oneului_bab/templates/user/find_Password.html
{% extends 'index.html' %}
{% load static %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script>
    $.ajaxSetup({
        headers: { "X-CSRFToken": '{{csrf_token}}' }
    });
</script>
{% endblock script %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/find_account.css' %}">
{% endblock css %}

{% block ad1 %}
{% endblock ad1 %}

{% block account_info %}
<div class="findaccount_container">
    <form class="findaccount_form" method="POST">
        <h3>비밀번호 찾기</h3>
        <div>아이디는 가입하신 이메일과 동일합니다.</div>
        <div class="find_password_info">이메일</div>
        <input class="find_password_input" type="email" name="email" required value="{{email}}">
        <div class="find_password_info">이름</div>
        <input class="find_password_input" type="text" name="name" required value="{{name}}">
        <div class="find_password_info">생년월일</div>
        <div class="find_password_input" id="birthdate_info">
            <input class="find_password_info_birthdate" type="text" name="birthdate_year" required value="{{birthdate_year}}">
            <select class="find_password_info_birthdate" name="birthdate_month" required>
                <option value="" {% if not birthdate_month %}selected{% endif %} disabled hidden>월</option>
                <option value="1" {% if birthdate_month == '1' %}selected{% endif %}>1월</option>
                <option value="2" {% if birthdate_month == '2' %}selected{% endif %}>2월</option>
                <option value="3" {% if birthdate_month == '3' %}selected{% endif %}>3월</option>
                <option value="4" {% if birthdate_month == '4' %}selected{% endif %}>4월</option>
                <option value="5" {% if birthdate_month == '5' %}selected{% endif %}>5월</option>
                <option value="6" {% if birthdate_month == '6' %}selected{% endif %}>6월</option>
                <option value="7" {% if birthdate_month == '7' %}selected{% endif %}>7월</option>
                <option value="8" {% if birthdate_month == '8' %}selected{% endif %}>8월</option>
                <option value="9" {% if birthdate_month == '9' %}selected{% endif %}>9월</option>
                <option value="10" {% if birthdate_month == '10' %}selected{% endif %}>10월</option>
                <option value="11" {% if birthdate_month == '11' %}selected{% endif %}>11월</option>
                <option value="12" {% if birthdate_month == '12' %}selected{% endif %}>12월</option>
            </select>
            <input class="find_password_info_birthdate" type="text" name="birthdate_days" required value="{{birthdate_days}}">
        </div>
        <div class="join_info_input" id="emailsend_box">
            <input class="join_info_input" id="emailcode" type="text" name="emailcode" placeholder="인증번호를 입력하세요">
            {% csrf_token %}
            <button class="join_info_input" id="emailsendbutton" type="submit" name="submit" value="email_verify">인증하기</button>
        </div>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% csrf_token %}
        <button class="find_password_input" id="find_password_button" type="submit" name="submit" value="search_password">비밀번호 찾기</button>
    </form>
    <div class="info_find_warp">
        <a class="info_find" href="/user/findid">아이디 찾기</a>
        <div class="info_find">|</div>
        <a class="info_find" href="/user/findpassword">비밀번호 찾기</a>
        <div class="info_find">|</div>
        <a class="info_find" href="/user/join">회원가입</a>
    </div>
</div>
{% endblock account_info %}

oneului_bab/templates/user/join.html
{% extends 'index.html' %}
{% load static %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script>
    $.ajaxSetup({
        headers: { "X-CSRFToken": '{{csrf_token}}' }
    });
</script>
{% endblock script %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/join.css' %}">
{% endblock css %}

{% block ad1 %}
{% endblock ad1 %}

{% block account_info %}
<div class="findaccount_container">
    <form class="findaccount_form" method="POST" id="join_form">
        <h3>회원가입</h3>
        <div>
            <div class="join_info">이메일</div>
            <input class="join_info_input" type="email" name="email" required value="{{email}}">
            <div class="join_info">비밀번호</div>
            <input class="join_info_input" type="password" name="password" required value="{{password}}">
            <div class="join_info">비밀번호 재확인</div>
            <input class="join_info_input" type="password" name="confirm_password" required value="{{confirm_password}}">
            <div class="join_info">이름</div>
            <input class="join_info_input" type="text" name="name" required value="{{name}}">
            <div class="join_info">닉네임</div>
            <input class="join_info_input" type="text" name="nickname" required value="{{nickname}}">
            <div class="join_info">생년월일</div>
            <div class="join_info_input">
                <input class="join_info_birthdate" type="text" name="birthdate_year" required value="{{birthdate_year}}">
                <select class="join_info_birthdate" name="birthdate_month" required>
                    <option value="" {% if not birthdate_month %}selected{% endif %} disabled hidden>월</option>
                    <option value="1" {% if birthdate_month == '1' %}selected{% endif %}>1월</option>
                    <option value="2" {% if birthdate_month == '2' %}selected{% endif %}>2월</option>
                    <option value="3" {% if birthdate_month == '3' %}selected{% endif %}>3월</option>
                    <option value="4" {% if birthdate_month == '4' %}selected{% endif %}>4월</option>
                    <option value="5" {% if birthdate_month == '5' %}selected{% endif %}>5월</option>
                    <option value="6" {% if birthdate_month == '6' %}selected{% endif %}>6월</option>
                    <option value="7" {% if birthdate_month == '7' %}selected{% endif %}>7월</option>
                    <option value="8" {% if birthdate_month == '8' %}selected{% endif %}>8월</option>
                    <option value="9" {% if birthdate_month == '9' %}selected{% endif %}>9월</option>
                    <option value="10" {% if birthdate_month == '10' %}selected{% endif %}>10월</option>
                    <option value="11" {% if birthdate_month == '11' %}selected{% endif %}>11월</option>
                    <option value="12" {% if birthdate_month == '12' %}selected{% endif %}>12월</option>
                </select>
                <input class="join_info_birthdate" type="text" name="birthdate_days" required value="{{birthdate_days}}">
            </div>
            <div class="join_info_input" id="emailsend_box">
                <input class="join_info_input" id="emailcode" type="text" name="emailcode" placeholder="인증번호를 입력하세요">
                {% csrf_token %}
                <button class="join_info_input" id="emailsendbutton" type="submit" name="submit" value="email-verify">인증하기</button>
            </div>
        </div>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% csrf_token %}
        <button class="join_info_input" id="join_button" type="submit" name="submit" value="join">가입하기</button>
    </form>
    <div class="info_find_warp">
        <a class="info_find" href="/user/findid">아이디 찾기</a>
        <div class="info_find">|</div>
        <a class="info_find" href="/user/findpassword">비밀번호 찾기</a>
        <div class="info_find">|</div>
        <a class="info_find" href="/user/join">회원가입</a>
    </div>
</div>
{% endblock account_info %}


{% block javascript %}
<script src="{% static 'js/join.js' %}"></script>
{% endblock javascript %}

oneului_bab/templates/user/userdetail.html
{% extends 'index.html' %}

{% block content %}
<h1>이메일 : {{ user.email }}</h1>
<h1>이름 : {{ user.name }}</h1>
<h1>닉네임 : {{ user.nickname }}</h1>   
<h1>생년월일 : {{ user.birth_date }}</h1>   
<h1>가입일 : {{ user.date_joined }}</h1>   
<h1>pk : {{ user.pk }}</h1>  
<hr>
<a href="{% url 'update' pk=user.pk %}">정보 수정</a>
<a href="{% url 'changepassword' pk=user.pk %}">비밀번호 변경</a>
{% endblock content %}


oneului_bab/templates/user/userpasswordchange.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <div class="form_group">
            <label for="id_password">현재 비밀번호</label>
            <input class="form_control" id="id_password" type="password" name="password" required>
        </div>
        <div class="form_group">
            <label for="id_password">새 비밀번호</label>
            <input class="form_control" id="id_password" type="password" name="newpassword" required>
        </div>
        <div class="form_group">
            <label for="id_password_check">새 비밀번호 재확인</label>
            <input class="form_control" id="id_password_check" type="password" name="confirm_newpassword" required>
        </div>
        {% if request.user == user %}
            {% csrf_token %}
            <button class="btn_save" type="submit" name="submit" value="btn_save">저장</button>
            <button class="btn_delete" type="submit" name="submit" value="btn_delete">회원 탈퇴</button>
        {% endif %}
    </form>
{% endblock content %}

oneului_bab/templates/user/userupdate.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <div class="form_group">
            <label for="id_name">이름</label>
            <div class="form_control" id="id_name" name="name">{{ user.name }}</div>
        </div>
        <div class="form_group">
            <label for="id_nickname">닉네임</label>
            <input type="text" class="form_control" id="id_nickname" name="nickname" value="{{ user.nickname }}" required>
        </div>
        <div class="form_group">
            <label for="id_birth_date">생년월일</label>
            <input type="date" class="form_control" id="id_birth_date" name="birth_date" value="{{ parsed_date }}" required>
        </div>
        <div class="form_group">
            <label for="id_password">비밀번호</label>
            <input class="form_control" id="id_password" type="password" name="password" required value="{{password}}">
        </div>
        <div class="form_group">
            <label for="id_password_check">비밀번호 재확인</label>
            <input class="form_control" id="id_password_check" type="password" name="confirm_password" required value="{{confirm_password}}">
        </div>
        {% if request.user == user %}
            {% csrf_token %}
            <button class="btn_save" type="submit" name="submit" value="btn_save">저장</button>
            <button class="btn_delete" type="submit" name="submit" value="btn_delete">회원 탈퇴</button>
        {% endif %}
    </form>
{% endblock content %}